# Generated by Django 3.2.11 on 2022-02-23 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import newstock.models


class Migration(migrations.Migration):

    dependencies = [
        ('newstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstock',
            name='invoice',
            field=models.ImageField(default=datetime.datetime(2022, 2, 23, 12, 40, 21, 27021, tzinfo=utc), upload_to=newstock.models.user_directory_path),
            preserve_default=False,
        ),
    ]
